### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by mihaibujanca** [rhashimoto/TangoFrameCapture#1]
Hello

I am trying to save as many frames as possible using the tango camera. Currently the best I got was about 1Hz using this code. I know glreadpixels is really slow, but is it supposed to slow it down this much? I don't really need to see the preview, all I care about is getting as many frames as possible saved to files.
Thanks

**Comment by rhashimoto** [comment]
I wrote this code for single frame captures, and it is meant to be clear, not fast.

`glReadPixels()` is slow, but my guess is that most of the time is spent in `Bitmap.compress()` and the file system. You should be able to test that by logging `glReadPixels()` and commenting out the save in your code. If I were trying to capture frames as fast as possible, I would (1) use the NDK instead of Java, and (2) buffer frames in RAM to write after capture is complete (assuming your captures are short enough to fit into RAM).
